apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  namespace: default

spec:
  replicas: 3

  selector:
    matchLabels:
      app: hello-app

  template:
    metadata:
      labels:
        app: hello-app

    spec:
      containers:
        - name: hello-app
          image: ghcr.io/cheating-at-solitaire/pipeline-lab:bcd8c0a940d0c2e493fb9c762ec667da27a31829
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 3000

          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
