apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  namespace: default

spec:
  replicas: 3

  selector:
    matchLabels:
      app: hello-app

  template:
    metadata:
      labels:
        app: hello-app

    spec:
      containers:
        - name: hello-app
          image: ghcr.io/cheating-at-solitaire/pipeline-lab:72b3f75f19a8ce909df48508530b6f58e326a8ce
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 3000

          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
